# Generated by Django 2.2.5 on 2019-10-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True)),
                ('year_model', models.IntegerField()),
                ('autogeartype', models.BooleanField(default=True)),
                ('doors', models.SmallIntegerField(default=4)),
                ('seats', models.SmallIntegerField()),
                ('base_price', models.PositiveIntegerField(blank=True, default=1)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_date', models.DateTimeField()),
                ('last_modified', models.DateTimeField()),
                ('first_name', models.CharField(blank=True, max_length=10)),
                ('last_name', models.CharField(blank=True, max_length=10)),
                ('age', models.IntegerField(blank=True)),
                ('start_date', models.DateTimeField()),
                ('number_of_days', models.IntegerField(default=1)),
                ('location', models.CharField(choices=[('Amman', 'Amman'), ('Aqaba', 'Aqaba'), ('Irbid', 'Irbid')], max_length=256)),
                ('offer', models.ManyToManyField(related_name='reservervations', to='cars.CarModel')),
                ('reserver', models.ForeignKey(on_delete='CASCADE', to='accounts.User')),
            ],
        ),
    ]
