# Generated by Django 2.2.5 on 2019-10-29 10:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20191029_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationmodel',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name='reservationmodel',
            name='offer',
        ),
        migrations.AddField(
            model_name='reservationmodel',
            name='offer',
            field=models.ForeignKey(default=1, on_delete='CASCADE', related_name='reservervations', to='cars.CarModel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservationmodel',
            name='ordered_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reservationmodel',
            name='reserver',
            field=models.ForeignKey(on_delete='CASCADE', related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
    ]
