# Generated by Django 2.2.5 on 2019-11-02 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20191101_1908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodel',
            options={'default_permissions': ('change', 'add', 'delete', 'view')},
        ),
    ]
