# Generated by Django 2.2.5 on 2019-11-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_auto_20191102_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarCommercialModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_title', models.CharField(max_length=128)),
                ('ar_title', models.CharField(max_length=128)),
                ('featured', models.BooleanField()),
                ('days', models.SmallIntegerField(default=3)),
                ('price', models.DecimalField(decimal_places=2, default=29.99, max_digits=6)),
                ('car', models.ForeignKey(on_delete='CASCADE', related_name='commercials', to='cars.CarModel')),
            ],
        ),
    ]
