# Generated by Django 2.2.5 on 2019-11-04 20:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_carcommercialmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='carcommercialmodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carcommercialmodel',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
